directories:
  output: release
  buildResources: build
appId: com.nofal.interval-timer
productName: Interval Timer
files:
  - filter:
      - dist/**/*
      - electron/**/*
linux:
  target:
    - target: AppImage
      arch:
        - x64
  category: Utility
  executableName: interval-timer
  executableArgs:
    - '--no-sandbox'
    - '--disable-setuid-sandbox'
    - '--disable-dev-shm-usage'
electronVersion: 40.7.0
